name: mlops
channels:
  - conda-forge
  - defaults
dependencies:
  # Core ML packages
  - python=3.11
  - pandas
  - scikit-learn
  - numpy
  - scipy
  - ipykernel
  # Visualization
  - seaborn
  - matplotlib
  - missingno
  - lxml
  - unidecode
  - pytest
  - fastapi
  - uvicorn
  - dvc
  - faiss-cpu
  - pip
  - pytorch
  - streamlit
  # Pip packages
  - pip:
      - newspaper3k
      - feedparser
      - lxml_html_clean
      - huggingface-hub
      - transformers
      - sentence-transformers
