name: CI-chatbotv1

on:
  push:
    branches: [ chatbotv1 ]
  pull_request:
    branches: [ chatbotv1 ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn dvc faiss-cpu pytest transformers sentence-transformers huggingface-hub torch Unidecode

      - name: Run unit tests
        run: |
          pytest -q

      - name: DVC repro
        run: |
          if [ -f data/processed/articles_cleaned.json ]; then
            echo "Processed data present: building index only";
            dvc repro index -f;
          elif [ -f data/raw/articles.json ]; then 
            echo "Raw data present: running preprocess and index";
            dvc repro preprocess index -f;
          else
            echo "No data found. Skipping DVC stages.";
          fi

      - name: Build Docker image (local)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: local/mlops-chatbot:chatbotv1

      - name: Log in to GHCR
        if: github.ref == 'refs/heads/chatbotv1'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (GHCR)
        if: github.ref == 'refs/heads/chatbotv1'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:chatbotv1
            ghcr.io/${{ github.repository }}:chatbotv1-${{ github.sha }}
